SAMPLE_XLSX_PATH = 'data/excel/sample.xlsx'
SAMPLE_SVG_PATH = 'data/svg/sample.svg'
SAMPLE_SVG_SCALED_PATH = 'data/svg/sample_scaled.svg'
LOGO_PATH = 'data/images/logo.ico'
CONFIG_PATH = 'data/json/config.json'
TEMP_XLSX_PATH = 'data/excel/temp.xlsx'
